---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: tf-controller-aws-lambda
spec:
  interval: 3m
  path: ./terraform/lambda
  approvePlan: "auto"
  varsFrom:
    - kind: Secret
      name: terraform-aws-keys
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: lambda-terraform-output